### ISSUE TITLE
Not updated to last game version?

### ISSUE THREAD

**Issue by lordSeaworth** [blind-coder/pz-mapmap#1]
Is it possible it doesn't work with latest project zomboid as of today? 36.4?

**Comment by blind-coder** [comment]
It should work with the .lotpack files, but the savegames most certainly don't work at the moment.

**Comment by lordSeaworth** [comment]
Can't seem to get it running with a normal map.

Keep getting 'Input string was not in a correct format.'
And i'm not quite sure what the parameters should be in the runme.bash

**Comment by blind-coder** [comment]
What is the command line you call the program with?

**Comment by lordSeaworth** [comment]
I'm just trying to use the example from runme.bash.
https://dl.dropboxusercontent.com/u/38136751/runme.bash

I've messed with different kinda of values. I just don't seem to undestand what files it exactly needs with the new update since some files don't exist anymore or i can't find some of them that are needed.

**Comment by blind-coder** [comment]
*mutters something about taking shortcuts in code*

If you are on Linux, you can create some symlinks like this:
```
[07:28:41][blindcoder@victoria:~/Projects/Mapping/MapMap/tiledef]$ ll
total 16
lrwxrwxrwx 1 blindcoder blindcoder 82 Jul 23  2015 0_tiledefinitions.tiles -> /home/blindcoder/Zomboid/ProjectZomboid/projectzomboid/media/tiledefinitions.tiles
lrwxrwxrwx 1 blindcoder blindcoder 85 Jul 23  2015 1_newtiledefinitions.tiles -> /home/blindcoder/Zomboid/ProjectZomboid/projectzomboid/media/newtiledefinitions.tiles
lrwxrwxrwx 1 blindcoder blindcoder 90 Jul 23  2015 2_tiledefinitions_erosion.tiles -> /home/blindcoder/Zomboid/ProjectZomboid/projectzomboid/media/tiledefinitions_erosion.tiles
lrwxrwxrwx 1 blindcoder blindcoder 88 Mar  3  2016 3_tiledefinitions_apcom.tiles -> /home/blindcoder/Zomboid/ProjectZomboid/projectzomboid/media/tiledefinitions_apcom.tiles
```
Otherwise, just cope the respective .tiles files to a directory and rename them as above. It's important that the numbers the files start with are exactly as shown above.
