### ISSUE TITLE
pz-deepzoom repository?

### ISSUE THREAD

**Issue by R4to0** [blind-coder/pz-mapmap#3]
The readme file mentions another repository that was supposed to be a continuation of it, however such repository doesn't exist. Was it renamed, moved or deleted?

https://github.com/blind-coder/pz-mapmap/blob/master/README.md?plain=1#L53

**Comment by blind-coder** [comment]
Ah, sorry, it was renamed deepzoom-utils. I updated the link to https://github.com/blind-coder/deepzoom-utils
