### ISSUE TITLE
Tracking down trees/bushes offset issue

### ISSUE THREAD

**Issue by R4to0** [blind-coder/pz-mapmap#7]
I've been trying to find where the offsets for the trees and vegetations is done because they're off from where it should be and 'leaking' out of the tile for some reason.

Here's an example:
![image](https://user-images.githubusercontent.com/3608184/164204837-e8f86154-c4da-4c7d-9d24-dd1e2c186923.png)

and the 'leak' i said in the borders:
![image](https://user-images.githubusercontent.com/3608184/164204985-e58d5113-c404-4871-810f-aa859545b22f.png)

Another example:
![image](https://user-images.githubusercontent.com/3608184/164205133-567ad2c3-3666-477a-a225-39b84279d90a.png)

Could try to fix myself but just wasted a few hours trying to find where the positions are stored (inside map itself with no correction applied?). Played around with the part where it draws the vegetation which touched the random generated bushes and tress but it didn't helped with normal trees that seems to be from the map itself like this part:
![image](https://user-images.githubusercontent.com/3608184/164205713-762caa55-b934-4fde-af43-d2f7a2d2dff2.png)

Any ideas where I should start?

**Comment by blind-coder** [comment]
Wow, never noticed this myself.
It's probably not worth tracking down as this tool is getting deprecated in favor of https://github.com/blind-coder/pzmap2dzi

**Comment by R4to0** [comment]
Oh I might give a try on the new one but I'm comfortable enough with the current mapmap solution :)
